spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://34.87.65.220:3306/yourclinicdb?useSSL=false
    username: dbadmin
    password: dbadmin
    name: com.mysql.jdbc.Driver
    jmx-enabled: true
    hikari:
      connection-init-sql: SELECT 1 FROM DUAL
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 10000
      idle-timeout: 60000
      max-lifetime: 600000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  jackson:
    serialization:
      fail-on-empty-beans: false


server:
  port: 8779
  servlet:
    context-path: /clinic

#logging:
#  config: classpath:log4j2.xml